x-bwrap-security: &bwrap-security
  cap_add:
    - SYS_ADMIN
  security_opt:
    - apparmor=unconfined
    - seccomp=unconfined

services:
  nanoinfra-gateway:
    <<: *bwrap-security

  nanoinfra-api:
    <<: *bwrap-security

  nanoinfra-cli:
    <<: *bwrap-security
