export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

export type UITurnPhase = "user" | "reasoning" | "activity" | "answer" | "complete";
export type MessageDeliveryStatus = "sending" | "accepted" | "failed";
export type MessageDeliveryErrorKind =
  | "message_too_big"
  | "workspace_scope_rejected"
  | "turn_rejected";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessageSource { kind: "cron" | "local_trigger" | "trigger" | string; label?: string; }

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** Structured tool events behind trace rows. Kept so activity cards can
   * distinguish running, completed, and failed tool phases. */
  toolEvents?: ToolProgressEvent[];
  /** Activity rows: explicit file edits emitted by edit tools. */
  fileEdits?: UIFileEdit[];
  /** Activity rows created during the same agent phase share one collapsible block. */
  activitySegmentId?: string;
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** App-specific CLI adapters explicitly attached to this user turn. */
  cliApps?: UICliAppAttachment[];
  /** Settings-managed MCP presets explicitly attached to this user turn. */
  mcpPresets?: UIMcpPresetAttachment[];
  /** Persisted sessions explicitly referenced by this user turn. */
  sessionMentions?: SessionMention[];
  resourceMentions?: ResourceMention[];
  /** Assistant turn: accumulated model reasoning / thinking text. Built up
   * incrementally from ``reasoning_delta`` frames; finalized when
   * ``reasoning_end`` arrives. */
  reasoning?: string;
  /** True while ``reasoning_delta`` frames are still arriving for this turn.
   * Drives the shimmer header on ``ReasoningBubble``. */
  reasoningStreaming?: boolean;
  /** End-to-end wall time for this assistant turn (persisted ``latency_ms`` / ``turn_end``). */
  latencyMs?: number;
  /** Client epoch milliseconds when the definitive ``turn_end`` was received. */
  completedAt?: number;
  /** Lightweight provenance for proactive assistant messages. */
  source?: UIMessageSource;
  /** Stable protocol metadata for grouping all activity emitted by one user turn. */
  turnId?: string;
  turnPhase?: UITurnPhase;
  turnSeq?: number;
  /** Ephemeral delivery lifecycle for optimistic user messages. */
  deliveryStatus?: MessageDeliveryStatus;
  /** Structured rejection reason shown with a failed optimistic message. */
  deliveryErrorKind?: MessageDeliveryErrorKind;
}

export interface UICliAppAttachment {
  name: string;
  display_name?: string;
  category?: string;
  entry_point?: string;
  logo_url?: string | null;
  brand_color?: string | null;
}

export interface UIMcpPresetAttachment {
  name: string;
  display_name?: string;
  category?: string;
  transport?: string;
  status?: string;
  configured?: boolean;
  logo_url?: string | null;
  brand_color?: string | null;
}

/** What the agent receives for an `@server:` or `@diagram:` mention: the id, never the name. */
export interface ResourceMention {
  kind: "server" | "diagram";
  id: string;
}

export interface SessionMention {
  /** Text token inserted in the composer, without the leading @. */
  name: string;
  /** Stable persisted-session identifier used by read_session. */
  session_key: string;
  title: string;
}

export interface SessionAutomationJob {
  id: string;
  name: string;
  enabled: boolean;
  protected?: boolean;
  delete_after_run?: boolean;
  created_at_ms?: number | null;
  updated_at_ms?: number | null;
  kind?: "local_trigger" | "cron" | string;
  schedule: {
    kind: "at" | "every" | "cron" | "local" | string;
    at_ms?: number | null;
    every_ms?: number | null;
    expr?: string | null;
    tz?: string | null;
  };
  payload: {
    message: string;
    kind?: "agent_turn" | "system_event" | "local_trigger" | string;
    command?: string;
  };
  state: {
    next_run_at_ms?: number | null;
    last_run_at_ms?: number | null;
    last_status?: "ok" | "error" | "skipped" | string | null;
    last_error?: string | null;
    pending?: boolean;
    run_history?: Array<{
      run_at_ms: number;
      status: "ok" | "error" | "skipped" | string;
      duration_ms?: number;
      error?: string | null;
    }>;
  };
  delivery?: AutomationDeliveryPolicy | string;
  skills?: string[];
  references?: ResourceMention[];
  commissioning?: AutomationCommissioning;
  origin?: {
    session_key?: string;
    channel: string;
    chat_id?: string;
    title?: string;
    preview?: string;
  } | null;
  trigger?: {
    id: string;
    command: string;
  };
}

/** A standing grant, in the shape `gates.standingGrants` takes. */
export interface ProposedGrant {
  id?: string | null;
  contexts: string[];
  hosts: string[];
  commands: string[];
}

/**
 * What a commissioning run found about one automation.
 *
 * `unchecked` also covers every automation created before commissioning existed, so it must never
 * be rendered as a problem. `error` means the rehearsal itself did not finish, which is not the
 * same as the automation being refused.
 */
export interface AutomationCommissioning {
  status: "unchecked" | "ok" | "refused" | "error" | string;
  checkedAtMs?: number | null;
  finding?: string;
  fingerprint?: string;
  proposedGrants?: ProposedGrant[];
}

export interface CommissioningResult {
  id: string;
  name: string;
  refused: boolean;
  commissioning: AutomationCommissioning;
}

export interface GrantPromotionResult {
  granted: ProposedGrant[];
  note: string;
  requires_restart: boolean;
}

export interface SessionAutomationsPayload { jobs: SessionAutomationJob[]; }
export interface AutomationsPayload { jobs: SessionAutomationJob[]; }
export type AutomationDeliveryPolicy = "always" | "on-change" | "on-error" | "never";

export interface AutomationUpdatePayload {
  name?: string;
  message?: string;
  delivery?: AutomationDeliveryPolicy;
  skills?: string[];
  references?: ResourceMention[];
  schedule?: {
    kind: "at" | "every" | "cron";
    at_ms?: number;
    every_ms?: number;
    expr?: string;
    tz?: string;
  };
}

export interface SessionDeleteResult {
  deleted: boolean;
  blocked_by_automations?: boolean;
  automations?: SessionAutomationJob[];
}

export interface SkillSummary {
  name: string;
  description: string;
  source: "workspace" | "builtin" | string;
  enabled?: boolean;
  deletable?: boolean;
  available: boolean;
  unavailable_reason?: string;
}

export interface SkillRequirements {
  bins: string[];
  env: string[];
  missing_bins: string[];
  missing_env: string[];
}

export interface SkillInstallOption {
  id: string;
  kind: string;
  label: string;
  command: string;
}

export interface SkillDetail extends SkillSummary {
  requirements: SkillRequirements;
  install_options?: SkillInstallOption[];
  raw_markdown: string;
}

export interface SkillsPayload { skills: SkillSummary[]; }

export interface SkillActionPayload extends SkillsPayload {
  last_action: {
    name: string;
    enabled: boolean;
    deleted: boolean;
  };
}

export interface MarketplaceSkillSummary {
  id: string;
  skill_id: string;
  name: string;
  source: string;
  provider: Exclude<MarketplaceProvider, "all">;
  installs: number;
  downloads?: number;
  url: string;
  installed: boolean;
  install_supported: boolean;
  metric: "installs_24h" | "installs_total";
  version?: string;
  verified?: boolean;
  requires_api_key?: boolean;
  rank?: number;
}

export type MarketplaceProvider = "all" | "skills_sh" | "nanoinfra";

export interface SkillsSearchPayload {
  query: string;
  skills: MarketplaceSkillSummary[];
  provider: MarketplaceProvider;
  install_supported: boolean;
}

export interface SkillsTrendingPayload {
  skills: MarketplaceSkillSummary[];
  period: "24h" | "trending" | "mixed";
  provider: MarketplaceProvider;
  install_supported: boolean;
}

export interface SkillsTrendsPayload {
  trends: Record<string, number[]>;
}

export interface SkillInstallPayload extends SkillsPayload {
  last_action: {
    installed: boolean;
    already_installed: boolean;
    name: string;
  };
}

/** Structured UI blob on ``progress`` WS frames; channels may add more ``kind`` values later. */
export interface AgentUIBlob {
  kind: string;
  data?: unknown;
}

/** WebSocket snapshot for sustained goals (`goal_state` events; keyed by ``chat_id``). */
export interface GoalStateWsPayload {
  active: boolean;
  ui_summary?: string;
  objective?: string;
}

export interface ToolProgressEvent {
  version?: number;
  phase?: "start" | "end" | "error" | string;
  call_id?: string;
  name?: string;
  arguments?: unknown;
  result?: unknown;
  error?: unknown;
  files?: unknown[];
  embeds?: unknown[];
}

export interface UIFileDiff {
  format: "unified" | string;
  context?: number;
  truncated?: boolean;
  text?: string;
}

export interface UIFileEdit {
  version?: number;
  call_id: string;
  tool: string;
  path: string;
  absolute_path?: string;
  phase?: "start" | "end" | "error" | string;
  added: number;
  deleted: number;
  approximate?: boolean;
  status: "editing" | "done" | "error";
  operation?: "edit" | "delete" | string;
  binary?: boolean;
  error?: string;
  pending?: boolean;
  diff?: UIFileDiff;
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
  /** Model preset persisted for this session; null means it still follows the global default. */
  modelPreset?: string | null;
  /** Unix epoch seconds when this session currently has a turn in flight. */
  runStartedAt?: number | null;
  workspaceScope?: WorkspaceScopePayload | null;
}

export type WorkspaceAccessMode = "restricted" | "full";
export type WebuiDefaultAccessMode = "default" | "full";

export interface WorkspaceScopePayload {
  project_path: string;
  project_name?: string;
  access_mode: WorkspaceAccessMode;
  restrict_to_workspace?: boolean;
  sandbox_status?: {
    restrict_to_workspace: boolean;
    workspace_root: string;
    level: string;
    enforced: boolean;
    provider: string;
    provider_label: string;
    summary: string;
  };
}

export interface WorkspacesPayload {
  schema_version: number;
  default_access_mode: WebuiDefaultAccessMode;
  default_scope: WorkspaceScopePayload;
  controls: {
    can_change_project: boolean;
    can_use_full_access: boolean;
  };
}

export type SidebarDensity = "comfortable" | "compact";
export type SidebarSortMode = "updated_desc" | "created_desc" | "title_asc" | "manual";

export interface SidebarViewState {
  density: SidebarDensity;
  show_previews: boolean;
  show_timestamps: boolean;
  show_archived: boolean;
  sort: SidebarSortMode;
}

export interface SidebarStatePayload {
  schema_version: number;
  pinned_keys: string[];
  archived_keys: string[];
  session_order: string[];
  title_overrides: Record<string, string>;
  project_name_overrides: Record<string, string>;
  tags_by_key: Record<string, string[]>;
  collapsed_groups: Record<string, boolean>;
  view: SidebarViewState;
  updated_at?: string | null;
}

export interface BootstrapResponse {
  token?: string;
  api_token?: string;
  ws_path: string;
  ws_url?: string | null;
  expires_in?: number;
  limits?: WebUIIngressLimits;
  model_name?: string | null;
  runtime_surface?: RuntimeSurface;
  runtime_capabilities?: RuntimeCapabilities;
}

export interface WebUITransportLimits {
  max_frame_bytes: number;
  envelope_reserve_bytes: number;
}

export interface WebUIMessageLimits {
  max_text_bytes: number;
}

export interface WebUIAttachmentLimits {
  max_count: number;
  max_file_bytes: number;
  max_total_bytes: number;
}

export interface WebUIIngressLimits {
  transport: WebUITransportLimits;
  message: WebUIMessageLimits;
  attachments: WebUIAttachmentLimits;
}

export type RuntimeSurface = "browser" | "native";
export type RestartBehavior = "none" | "nextTurn" | "engineRestart" | "appRestart";
export type SettingsApplyStatus =
  | "idle"
  | "pending"
  | "applying"
  | "restarting_engine"
  | "requires_app_restart";

export interface RuntimeCapabilities {
  can_restart_engine: boolean;
  can_pick_folder: boolean;
  can_open_logs: boolean;
  can_export_diagnostics: boolean;
}

export interface ProviderModelInfo {
  id: string;
  label?: string | null;
  description?: string | null;
  owned_by?: string | null;
  context_window?: number | null;
}

export interface ProviderModelsPayload {
  provider: string;
  label: string;
  status:
    | "available"
    | "unsupported"
    | "not_configured"
    | "missing_api_base"
    | "error";
  catalog_kind: "builtin" | "official" | "catalog" | "local" | "custom" | "unsupported";
  models: ProviderModelInfo[];
  model_count: number;
  message?: string | null;
  fetched_at?: number;
}

export interface ProviderOAuthAuthorizationRequired {
  status: "authorization_required";
  provider: string;
  flow_id: string;
  authorization_url: string;
  expires_in: number;
  completion_input?: "authorization_code" | "callback_url";
}

export interface ProviderOAuthPending {
  status: "pending";
  provider: string;
  flow_id: string;
}

export type ProviderOAuthLoginResult = SettingsPayload | ProviderOAuthAuthorizationRequired;
export type ProviderOAuthCompletionResult = SettingsPayload | ProviderOAuthPending;

/**
 * Capability gate payloads (nanoinfraorg/nanoinfra#26, #28, #29).
 *
 * Every key spelling matches the route payload, so no layer translates a policy key or a
 * record field. The gateway sends the policy inside ``advanced.gates``.
 */
export interface GatesScopePolicy {
  host: string;
  group: string;
  all: string;
}

export interface GatesContextPolicy {
  "mutate.remote": GatesScopePolicy;
  "mutate.inventory": string;
  "credential.access": string;
}

export interface GatesApprover {
  channel: string;
  sender: string;
}

export interface GatesStandingGrant {
  id?: string | null;
  contexts: string[];
  hosts: string[];
  commands: string[];
}

export interface GatesAuditPolicy {
  retentionDays: number;
  recordCommandText: boolean;
}

export interface GatesPolicy {
  approvers: GatesApprover[];
  approvalPaths: string[];
  interactive: GatesContextPolicy;
  unattended: GatesContextPolicy;
  standingGrants: GatesStandingGrant[];
  audit: GatesAuditPolicy;
}

/**
 * Which authentication the gateway installed -- nanoinfraorg/nanoinfra#85.
 *
 * The server sends a kind and never a sentence, because this app carries ten locales.
 */
export type GatesIdentityPosture = "no_proxy" | "verified" | "any_verified" | "plain";

/**
 * The posture of the deployment, and the actor of this request.
 *
 * `issuer` and `identityClaim` belong to a verified posture, and `assertionHeader` belongs to an
 * unverified one. A posture that has no such fact sends an empty string.
 *
 * `assertionMissing` is the warning. A proxy is configured, and the actor is the bare path name,
 * so the assertion did not arrive or did not verify.
 */
export interface GatesIdentity {
  posture: GatesIdentityPosture;
  issuer: string;
  identityClaim: string;
  assertionHeader: string;
  actor: string;
  assertionMissing: boolean;
}

export interface GatesPayload {
  policy: GatesPolicy;
  /**
   * Which rows still hold a shipped default, for the marker beside them.
   *
   * Optional on purpose (#86). It drives a marker and nothing else, so a gateway that answers
   * without it must still let an operator read and edit their policy. The optional type is what
   * makes every reader handle that: a guard that listed the required fields needed an edit for
   * every field the panel started reading, and the miss this fixes was exactly that edit being
   * forgotten.
   */
  from_default?: Record<string, boolean>;
  choices: {
    "mutate.remote": string[];
    "mutate.inventory": string[];
    "credential.access": string[];
    all: string[];
  };
  /** An older gateway sends no block, and the panel then shows no Identity section. */
  identity?: GatesIdentity;
}

export interface GatesLatchAttempt {
  at: string | null;
  digest: string | null;
  tool: string | null;
}

export interface GatesLatchEntry {
  attempts: GatesLatchAttempt[];
  capabilityClass: string;
  deniedAt: string | null;
  deniedBy: string | null;
  reason: string | null;
  refusals: number;
  sessionId: string;
}

export interface GatesLatchPayload {
  degraded: boolean;
  latches: GatesLatchEntry[];
  summary: string;
}

export interface GatesLatchClearValues {
  capabilityClass: string;
  sessionId: string;
}

export interface GatesLatchClearPayload {
  cleared?: boolean;
}

export interface GatesAuditRecord {
  ts: string | null;
  /** The name of this record. A completion record points at a decision record by this id. */
  recordId: string | null;
  /** The decision record a completion follows. It is null on a decision record. */
  follows: string | null;
  sessionId: string | null;
  executionContext: string | null;
  originPath: string | null;
  approvalPath: string | null;
  samePath: boolean;
  /**
   * The person the request came from, and the agent's claim about itself. `actor` is the person
   * who answered, and a trusted path authenticated them. This one nothing verified.
   */
  originActor: string | null;
  actor: string | null;
  capabilityClass: string | null;
  scope: string | null;
  hosts: string[];
  hostCount: number | null;
  commandDigest: string | null;
  commandText: string | null;
  holdsCommandText: boolean;
  decision: string | null;
  reason: string | null;
  grantId: string | null;
  tokenNonce: string | null;
  exitCode: number | null;
  durationMs: number | null;
  tool: string | null;
}

export interface GatesAuditPage {
  records: GatesAuditRecord[];
  total: number;
  limit: number;
  offset: number;
  recordsCommandText: boolean;
  choices: {
    decision: string[];
    capabilityClass: string[];
    executionContext: string[];
  };
}

/**
 * One suspended action, as the executor rendered it (nanoinfraorg/nanoinfra#27).
 *
 * `payload` holds the bytes the executor produced, and `targetDigest` binds them. The inbox
 * renders the payload as it arrives and echoes the digest back. It builds no summary of its own.
 */
export interface GatesPendingApproval {
  requestId: string;
  sessionId: string;
  originPath: string;
  executionContext: string;
  capabilityClass: string;
  scope: string;
  hostCount: number;
  hosts: string[];
  payload: string;
  targetDigest: string;
  expiresInS: number;
  samePath: boolean;
}

/** One suspended action with an absolute deadline, so the inbox counts the time down. */
export interface GatesPendingApprovalView extends GatesPendingApproval {
  expiresAt: number;
}

export interface GatesApprovalsPayload {
  degraded: boolean;
  approvalPath: string;
  count: number;
  pending: GatesPendingApproval[];
}

export type GatesApprovalDecision = "approve" | "deny";

export interface GatesApprovalAnswerValues {
  requestId: string;
  decision: GatesApprovalDecision;
  /** The digest of the payload the operator read. An approval carries it, a denial does not. */
  targetDigest?: string;
  reason?: string;
}

export interface GatesApprovalAnswer {
  ok: boolean;
  requestId: string;
  decision: string;
  actor: string;
  /** The rule that refused this answer, for the inbox to render. */
  refusal: string | null;
  error: string | null;
  degraded: boolean;
}

/** Audit filters. The route reads them from the query string. */
export interface GatesAuditQuery {
  decision?: string;
  capabilityClass?: string;
  executionContext?: string;
  /** One person, to read every action they raised. It is free text and not a choice. */
  originActor?: string;
  since?: string | null;
}

export interface SettingsPayload {
  surface?: RuntimeSurface;
  runtime_surface?: RuntimeSurface;
  runtime_capabilities?: RuntimeCapabilities;
  apply_state?: {
    status: SettingsApplyStatus;
    sections: string[];
  };
  restart_behavior_by_section?: Record<string, RestartBehavior>;
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
    model_preset: string | null;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    timezone: string;
    tool_hint_max_length: number;
    max_concurrent_subagents: number;
  };
  model_presets: Array<{
    name: string;
    label: string;
    active: boolean;
    is_default: boolean;
    model: string;
    provider: string;
    resolved_provider?: string | null;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    reasoning_effort_values?: string[];
  }>;
  model_call_order: string[];
  model_call_order_editable: boolean;
  created_model_preset?: string;
  created_provider?: string;
  providers: Array<{
    name: string;
    label: string;
    is_custom?: boolean;
    configured: boolean;
    auth_type?: "api_key" | "oauth";
    api_key_required?: boolean;
    api_key_hint?: string | null;
    api_base?: string | null;
    default_api_base?: string | null;
    model_selectable?: boolean;
    model_catalog?: ProviderModelsPayload["catalog_kind"];
    api_type?: "auto" | "chat_completions" | "responses";
    oauth_account?: string | null;
    oauth_expires_at?: number | null;
    oauth_login_supported?: boolean;
    proxy?: string | null;
    advanced_fields?: Array<
      | "api_type"
      | "extra_headers"
      | "extra_body"
      | "extra_query"
      | "proxy"
      | "thinking_style"
      | "region"
      | "profile"
    >;
    extra_headers?: Record<string, string> | null;
    extra_body?: Record<string, unknown> | null;
    extra_query?: Record<string, string> | null;
    thinking_style?: string | null;
    region?: string | null;
    profile?: string | null;
  }>;
  web_search: {
    provider: string;
    api_key_hint?: string | null;
    base_url?: string | null;
    max_results: number;
    timeout: number;
    providers: Array<{
      name: string;
      label: string;
      credential: "none" | "api_key" | "optional_api_key" | "base_url";
    }>;
  };
  web: {
    enable: boolean;
    proxy?: string | null;
    user_agent?: string | null;
    search: {
      max_results: number;
      timeout: number;
    };
    fetch: {
      use_jina_reader: boolean;
    };
  };
  api?: {
    host: string;
    port: number;
    timeout: number;
    api_key_hint?: string | null;
  };
  observability?: {
    provider: "langfuse" | string;
    configured: boolean;
    base_url: string;
  };
  image_generation: {
    enabled: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    default_aspect_ratio: string;
    default_image_size: string;
    max_images_per_turn: number;
    save_dir: string;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      auth_type?: "api_key" | "oauth";
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
      models?: string[];
      default_model?: string | null;
    }>;
  };
  transcription?: {
    enabled: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    language: string | null;
    max_duration_sec: number;
    max_upload_mb: number;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
    }>;
  };
  runtime: {
    config_path: string;
    workspace_path: string;
    gateway_host: string;
    gateway_port: number;
    heartbeat: {
      enabled: boolean;
      interval_s: number;
      keep_recent_messages: number;
    };
    dream: {
      schedule: string;
    };
    unified_session: boolean;
  };
  usage?: {
    days: Array<{
      date: string;
      prompt_tokens: number;
      completion_tokens: number;
      cached_tokens: number;
      total_tokens: number;
      provider_tokens?: number;
      estimated_tokens?: number;
      requests: number;
      provider_requests?: number;
      estimated_requests?: number;
      sources?: Record<
        "user" | "api" | "cron" | "dream" | "system" | string,
        {
          prompt_tokens: number;
          completion_tokens: number;
          cached_tokens: number;
          total_tokens: number;
          provider_tokens?: number;
          estimated_tokens?: number;
          requests: number;
          provider_requests?: number;
          estimated_requests?: number;
        }
      >;
    }>;
    total_tokens: number;
    total_tokens_30d: number;
    total_tokens_365d: number;
    peak_day_tokens: number;
    current_streak_days: number;
    longest_streak_days: number;
    active_days_30d: number;
    requests_30d: number;
    updated_at?: string | null;
  };
  advanced: {
    restrict_to_workspace: boolean;
    workspace_sandbox?: {
      restrict_to_workspace: boolean;
      workspace_root: string;
      level: "off" | "application" | "system" | string;
      enforced: boolean;
      provider: string;
      provider_label: string;
      summary: string;
    };
    ssrf_whitelist_count: number;
    webui_allow_local_service_access: boolean;
    allow_local_preview_access?: boolean;
    webui_default_access_mode: WebuiDefaultAccessMode;
    private_service_protection_enabled: boolean;
    mcp_server_count: number;
    exec_enabled: boolean;
    exec_sandbox?: string | null;
    exec_path_prepend_set: boolean;
    exec_path_append_set: boolean;
    /** An older gateway sends no gate block. The gate panel then stays away. */
    gates?: GatesPayload;
  };
  requires_restart: boolean;
  restart_required_sections?: Array<"runtime" | "browser" | "image">;
  version?: {
    current: string;
  };
  docs?: {
    version: string;
    base_url: string;
    chat_apps_url: string;
    latest_url?: string;
  };
}

export interface ApiServicePayload {
  installed: boolean;
  running: boolean;
  managed: boolean;
  host: string;
  port: number;
  timeout: number;
  api_key_hint?: string | null;
  endpoint: string;
  command: string;
  log_path?: string | null;
  last_action?: "started" | "stopped" | string;
}

export interface AppPackageRef {
  manager: string;
  name?: string;
}

export interface AppCapability {
  type: "cli" | "mcp" | "skill" | string;
  entry_point?: string;
  package?: AppPackageRef;
  path?: string;
  transport?: string;
  command?: string;
  args?: string[];
  url?: string;
  fields?: Array<{
    name: string;
    target?: string;
    required?: boolean;
    secret?: boolean;
    env_var?: string | null;
  }>;
}

export interface AppPlan {
  supported: boolean;
  strategy?: string;
  managed_paths?: string[];
  verification?: string[];
}

export interface AppTrust {
  registry: string;
  level: string;
  review_status: string;
}

export interface AppManifest {
  schema: "agent-app.v1" | string;
  id: string;
  display_name: string;
  version?: string;
  description: string;
  category: string;
  source: string;
  logo_url?: string | null;
  brand_color?: string | null;
  docs_url?: string | null;
  capabilities: AppCapability[];
  install: AppPlan;
  remove: AppPlan;
  trust: AppTrust;
}

export interface CliAppInfo {
  name: string;
  display_name: string;
  category: string;
  description: string;
  requires: string;
  source: string;
  entry_point: string;
  install_supported: boolean;
  installed: boolean;
  available: boolean;
  status: "installed" | "missing" | "available" | "unsupported" | "not_installed" | string;
  logo_url?: string | null;
  brand_color?: string | null;
  skill_installed: boolean;
  manifest?: AppManifest;
}

/** One installed Agent Plugins v1 package, as the read-only panel sees it. */
export interface AgentPluginInfo {
  name: string;
  display_name: string;
  description: string;
  repository: string;
  version: string;
  category: string;
  accent_color: string | null;
  logo: string | null;
  permissions: string[];
  skills: string[];
  mcp_servers: string[];
  /**
   * `modified` is the state worth showing: the package is listed in config but its content
   * changed since it was activated, so it deactivated itself and needs review. It looks like
   * "off" and it means something else.
   */
  state: "active" | "modified" | "inactive";
  declared: boolean;
}

export interface AgentPluginsPayload {
  plugins: AgentPluginInfo[];
  /** Names in `tools.agentPlugins` that no installed package provides. */
  unknown: string[];
  /** Always false. Activation lives in config, so this panel cannot change anything. */
  editable: boolean;
  authority: string;
  error?: string;
}

export interface CliAppsPayload {
  apps: CliAppInfo[];
  installed_count: number;
  catalog_updated_at?: string | null;
  catalog_refresh_pending?: boolean;
  last_action?: {
    ok: boolean;
    message: string;
    installed?: boolean;
    removed?: boolean;
    output?: string | null;
    still_available?: boolean;
    verification?: string[];
    verification_failed?: string[];
  };
}

export interface NanoinfraFeatureInfo {
  name: string;
  display_name: string;
  capabilities?: string[];
  settings_visible?: boolean;
  webui?: string;
  type: "channel" | "feature" | string;
  enabled: boolean;
  running?: boolean;
  runtime_status?: ChannelRuntimeStatus;
  runtime_error?: string;
  configured?: boolean;
  config_values?: Record<string, string>;
  configured_fields?: string[];
  setup?: ChannelSetupContract;
  instances?: NanoinfraChannelInstanceInfo[];
  installed: boolean;
  ready: boolean;
  status: "enabled" | "missing_dependency" | "not_enabled" | string;
  install_supported: boolean;
  requires_restart: boolean;
}

export interface ChannelSetupContractField {
  key: string;
  field: string;
  kind: "string" | "secret" | "int" | "bool" | "list" | "enum" | string;
  choices: string[];
  required: boolean;
  default_value?: string;
}

export interface ChannelSetupContract {
  fields: ChannelSetupContractField[];
  official_url?: string;
}

export interface NanoinfraChannelInstanceInfo {
  id: string;
  name: string;
  display_name?: string;
  avatar_url?: string;
  enabled: boolean;
  running?: boolean;
  runtime_status?: ChannelRuntimeStatus;
  runtime_error?: string;
  configured: boolean;
  config_values: Record<string, string>;
  configured_fields: string[];
}

export type ChannelRuntimeStatus = "running" | "starting" | "failed" | "stopped" | string;

export interface NanoinfraFeaturesPayload {
  features: NanoinfraFeatureInfo[];
  enabled_count: number;
  requires_restart?: boolean;
  last_action?: {
    ok: boolean;
    message: string;
    enabled?: boolean;
  };
}

export type ChannelSetupStatus =
  | "connected"
  | "configured"
  | "needs_setup"
  | "invalid"
  | "unsupported"
  | string;

export type ChannelValidationCheckStatus = "pass" | "warn" | "fail" | "skipped" | string;

export interface ChannelValidationCheck {
  id: string;
  label: string;
  status: ChannelValidationCheckStatus;
  message?: string;
  action_url?: string;
}

export interface ChannelIdentity {
  name?: string;
  workspace?: string;
  account?: string;
  avatar_url?: string;
}

export interface ChannelValidationPayload {
  name: string;
  status: ChannelSetupStatus;
  checks: ChannelValidationCheck[];
  identity?: ChannelIdentity;
  missing_fields: string[];
  can_enable: boolean;
  requires_restart: boolean;
  checked_at?: string;
  message?: string;
}

export interface PairingRequestInfo {
  code: string;
  channel: string;
  sender_id: string;
  created_at_ms?: number | null;
  expires_at_ms?: number | null;
  expires_in_seconds?: number | null;
}

export interface PairingPayload {
  requests: PairingRequestInfo[];
  last_action?: {
    ok: boolean;
    action: "approve" | "deny" | string;
    message: string;
    code?: string;
    channel?: string;
    sender_id?: string;
  };
}

export interface McpPresetField {
  name: string;
  label: string;
  secret: boolean;
  required: boolean;
  configured: boolean;
  placeholder?: string;
  env_var?: string | null;
}

export interface McpPresetInfo {
  name: string;
  display_name: string;
  category: string;
  description: string;
  docs_url: string;
  transport: "stdio" | "streamableHttp" | "sse" | "oauth" | string;
  requires: string;
  note: string;
  install_supported: boolean;
  installed: boolean;
  configured: boolean;
  available: boolean;
  status: "not_installed" | "configured" | "missing_credentials" | "missing_dependency" | "coming_soon" | string;
  logo_url?: string | null;
  brand_color?: string | null;
  required_fields: McpPresetField[];
  connection_summary: string;
  tool_count?: number;
  tool_names?: string[];
  checked_at?: string | null;
  error?: string | null;
  enabled_tools?: string[];
  source?: "preset" | "custom" | string;
  manifest?: AppManifest;
}

export interface McpPresetsPayload {
  presets: McpPresetInfo[];
  installed_count: number;
  requires_restart?: boolean;
  hot_reload?: {
    ok: boolean;
    message: string;
    added?: string[];
    changed?: string[];
    removed?: string[];
    retried?: string[];
    connected?: string[];
    configured?: string[];
    failed?: string[];
    tools_removed?: number;
    requires_restart?: boolean;
  };
  last_action?: {
    ok: boolean;
    message: string;
    installed?: boolean;
    removed?: boolean;
    managed_paths_removed?: string[];
    verification?: string[];
    verification_failed?: string[];
    tool_count?: number;
    tool_names?: string[];
    checked_at?: string | null;
    error?: string | null;
  };
}

export type ChannelConnectStatus = "pending" | "succeeded" | "expired" | "cancelled" | "failed";

export interface ChannelConnectPayload {
  session_id: string;
  instance_id?: string;
  status: ChannelConnectStatus;
  message?: string;
  qr_url?: string;
  domain?: string;
  interval_ms?: number;
  expires_at_ms?: number;
  app_id?: string;
  account?: string;
  nanoinfra_features?: NanoinfraFeaturesPayload;
}

export interface ChannelConfigurePayload {
  name: string;
  saved: boolean;
  saved_keys?: string[];
  nanoinfra_features?: NanoinfraFeaturesPayload;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
  modelPreset?: string | null;
  contextWindowTokens?: number;
  timezone?: string;
  toolHintMaxLength?: number;
  maxConcurrentSubagents?: number;
}

export interface ModelConfigurationCreate {
  name?: string;
  label: string;
  provider: string;
  model: string;
  maxTokens?: number;
  contextWindowTokens?: number;
  temperature?: number;
  reasoningEffort?: string | null;
}

export interface ModelConfigurationUpdate {
  name: string;
  label?: string;
  provider?: string;
  model?: string;
  maxTokens?: number;
  contextWindowTokens?: number;
  temperature?: number;
  reasoningEffort?: string | null;
}

export interface ProviderSettingsUpdate {
  provider: string;
  displayName?: string;
  apiKey?: string;
  apiBase?: string;
  apiType?: "auto" | "chat_completions" | "responses";
  proxy?: string;
  extraHeaders?: string;
  extraBody?: string;
  extraQuery?: string;
  thinkingStyle?: string;
  region?: string;
  profile?: string;
}

export interface ProviderCreationUpdate {
  name: string;
  apiKey?: string;
  apiBase: string;
  proxy?: string;
  extraHeaders?: string;
  extraBody?: string;
  extraQuery?: string;
  thinkingStyle?: string;
}

export interface WebSearchSettingsUpdate {
  provider: string;
  apiKey?: string;
  baseUrl?: string;
  maxResults?: number;
  timeout?: number;
  useJinaReader?: boolean;
}

export interface NetworkSafetySettingsUpdate {
  webuiAllowLocalServiceAccess: boolean;
  webuiDefaultAccessMode: WebuiDefaultAccessMode;
}

export interface ImageGenerationSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  defaultAspectRatio: string;
  defaultImageSize: string;
  maxImagesPerTurn: number;
}

export interface TranscriptionSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  language: string;
  maxDurationSec: number;
  maxUploadMb: number;
}

/**
 * Backend-owned contract for how a slash command affects WebUI turn state.
 *
 * - side_channel: returns control text without starting or ending an agent turn.
 * - finalize_active_turn: side-channel command that also closes the active UI turn.
 * - stop_active_turn: cancels the active turn; exact submits may be intercepted locally.
 * - agent_turn: always enters the normal agent path.
 * - agent_turn_with_args: no args is side-channel usage; args enter the agent path.
 */
export type SlashCommandLifecycle =
  | "side_channel"
  | "finalize_active_turn"
  | "stop_active_turn"
  | "agent_turn"
  | "agent_turn_with_args";

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
  lifecycle: SlashCommandLifecycle;
  acceptsArgs: boolean;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export interface InboundTurnMetadata {
  turn_id?: string;
  turn_phase?: UITurnPhase;
  turn_seq?: number;
}

export type InboundEvent =
  /**
   * ``operator_actor`` is the identity the gateway resolved for this connection (#70):
   * ``webui:<claim>`` behind a trusted proxy, and ``webui`` for a deployment with no proxy.
   * It is absent from an older gateway, and absent is not the same fact as ``webui``.
   */
  | { event: "ready"; chat_id: string; client_id: string; operator_actor?: string }
  | { event: "attached"; chat_id: string }
  | { event: "message_accepted"; chat_id: string; turn_id: string }
  | ({
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      tool_events?: ToolProgressEvent[];
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress" | "reasoning";
      /** Server-measured turn wall time when this frame finishes an assistant reply. */
      latency_ms?: number;
      /** Lightweight provenance for proactive assistant messages. */
      source?: UIMessageSource;
      /** Optional structured payload on progress frames (channel-specific). */
      agent_ui?: AgentUIBlob;
    } & InboundTurnMetadata)
  | ({
      event: "file_edit";
      chat_id: string;
      edits: UIFileEdit[];
    } & InboundTurnMetadata)
  | ({
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
      /** Lightweight provenance for proactive streamed assistant messages. */
      source?: UIMessageSource;
    } & InboundTurnMetadata)
  | ({
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
      text?: string;
      /** Lightweight provenance for proactive streamed assistant messages. */
      source?: UIMessageSource;
      /** This answer segment ended, but the active agent turn will continue. */
      resuming?: boolean;
      /** The next answer segment continues this same assistant message. */
      merge_next?: boolean;
    } & InboundTurnMetadata)
  | ({
      event: "reasoning_delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    } & InboundTurnMetadata)
  | ({
      event: "reasoning_end";
      chat_id: string;
      stream_id?: string;
    } & InboundTurnMetadata)
  | {
      event: "runtime_model_updated";
      model_name: string;
      model_preset?: string | null;
    }
  | {
      event: "turn_model_updated";
      chat_id: string;
      model_name: string;
    }
  | ({
      event: "turn_end";
      chat_id: string;
      latency_ms?: number;
      /** Authoritative sustained-goal snapshot for this chat (same shape as ``goal_state`` events). */
      goal_state?: GoalStateWsPayload;
    } & InboundTurnMetadata)
  | ({
      event: "goal_status";
      chat_id: string;
      /** Turn executing (user message through agent loop). */
      status: "running" | "idle";
      /** Server ``time.time()`` when ``status`` is ``running``. */
      started_at?: number;
    } & InboundTurnMetadata)
  | {
      event: "goal_state";
      chat_id: string;
      goal_state: GoalStateWsPayload;
    }
  | {
      /** A saved diagram changed server-side (agent tool, REST route, another tab). */
      event: "diagram_updated";
      diagram_id: string;
      kind: "created" | "updated" | "deleted" | string;
      /** Revision now on disk; absent for a delete. */
      revision?: number;
    }
  | {
      event: "session_updated";
      chat_id: string;
      scope?: "metadata" | "thread" | string;
      workspace_scope?: WorkspaceScopePayload;
    }
  | {
      event: "workspace_upload_result";
      request_id: string;
      /** The listing of the directory the file landed in. */
      listing: WorkspaceListingPayload;
    }
  | { event: "workspace_upload_error"; request_id?: string; detail: string }
  | { event: "transcription_result"; request_id: string; text: string }
  | {
      event: "transcription_error";
      request_id?: string;
      detail?: string;
      provider?: string;
    }
  | {
      event: "error";
      chat_id?: string;
      detail?: string;
      reason?: string;
      /** Present when this error rejects a specific outbound WebUI turn. */
      turn_id?: string;
    };

/** Base64-encoded file attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must use a server-whitelisted image, video, or document MIME
 * type. SVG remains rejected on ingress to avoid an embedded-script XSS
 * surface. ``name`` is advisory and is surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export interface OutboundCliAppMention {
  name: string;
  display_name?: string;
  category?: string;
  entry_point?: string;
  logo_url?: string | null;
  brand_color?: string | null;
}

export interface OutboundMcpPresetMention {
  name: string;
  display_name?: string;
  category?: string;
  transport?: string;
  status?: string;
  configured?: boolean;
  logo_url?: string | null;
  brand_color?: string | null;
}

/** Response shape for ``GET .../webui-thread`` (server-built transcript replay). */
export interface WebuiThreadPagePayload {
  before_cursor?: string | null;
  has_more_before?: boolean;
  loaded_message_count?: number;
  total_known_message_count?: number;
  user_message_offset?: number;
}

export interface WebuiThreadPersistedPayload {
  schemaVersion: number;
  sessionKey?: string;
  savedAt?: string;
  messages: UIMessage[];
  fork_boundary_message_count?: number;
  /** Turn ids backed by an explicit persisted ``turn_end`` event. */
  completed_turn_ids?: string[];
  has_pending_tool_calls?: boolean;
  /** Exact active turn when supplied by a current gateway. */
  active_turn_id?: string | null;
  page?: WebuiThreadPagePayload;
  workspace_scope?: WorkspaceScopePayload;
}

/** One child of a listed directory (`nanoinfra/webui/file_browser.py`). */
export interface WorkspaceEntry {
  name: string;
  kind: "file" | "directory" | "symlink" | "other";
  /** `null` for a directory, and for a child that could not be stat'ed. */
  size: number | null;
  modified: string | null;
  /** A symlink whose target leaves the workspace: listed, but not followable. */
  escapesWorkspace: boolean;
}

export interface WorkspaceListingPayload {
  /** Absolute path of the listed directory. */
  path: string;
  /** Workspace-relative path; empty at the root. */
  displayPath: string;
  projectPath: string;
  /** `null` at the workspace root, where there is no step up to offer. */
  parent: string | null;
  entries: WorkspaceEntry[];
  /** The directory held more children than one response carries. */
  truncated: boolean;
}

export interface FilePreviewPayload {
  path: string;
  display_path: string;
  project_path: string;
  language: string;
  content: string;
  size: number;
  truncated: boolean;
}

export type Outbound =
  | { type: "new_chat"; workspace_scope?: WorkspaceScopePayload }
  | { type: "fork_chat"; source_chat_id: string; before_user_index: number; title?: string }
  | { type: "attach"; chat_id: string }
  | {
      /**
       * One file into the workspace. Over the socket rather than HTTP because this
       * transport exposes no request body (see the chunked diagram headers in
       * `ws_http.py`), and bulk bytes do not belong in header lines.
       */
      type: "workspace_upload";
      request_id: string;
      /** Absolute directory path, or null for the workspace root. */
      parent: string | null;
      name: string;
      data_url: string;
    }
  | { type: "set_sidebar_state"; state: SidebarStatePayload }
  | { type: "set_workspace_scope"; chat_id: string; workspace_scope: WorkspaceScopePayload }
  | { type: "transcribe_audio"; request_id: string; data_url: string; duration_ms?: number }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      cli_apps?: OutboundCliAppMention[];
      mcp_presets?: OutboundMcpPresetMention[];
      session_mentions?: SessionMention[];
      quoted_context?: string;
      workspace_scope?: WorkspaceScopePayload;
      turn_id?: string;
      /** Marks messages sent by the embedded WebUI, without changing the
       * generic websocket protocol for other clients. */
      webui?: true;
    };
